import React from 'react';
import './Automation.css';

const Automation = () => {
    return (
        <div className="extrapages-section">
            <section className="body-part">
                <div class="flex space-between">
                    <div class="part-one-left flex space-between">
                        <select name="selectList" class="select-list">
                            <option value="1" >Contract 1</option>
                            <option value="2" >Contract 2</option>
                            <option value="3" >Contract 3</option>
                            <option value="4" >Contract 4</option>
                            <option value="5" >Contract 5</option>
                            <option value="6" >Contract 6</option>
                            <option value="7" >Contract 7</option>
                        </select>
                    </div>
                    <div class="part-one-left flex space-between">
                        <select name="selectList" class="select-list">
                            <option value="1" >Contract 1</option>
                            <option value="2" >Contract 2</option>
                            <option value="3" >Contract 3</option>
                            <option value="4" >Contract 4</option>
                            <option value="5" >Contract 5</option>
                            <option value="6" >Contract 6</option>
                            <option value="7" >Contract 7</option>
                        </select>
                    </div>
                    <div class="part-one-left flex space-between">
                        <select name="selectList" class="select-list">
                            <option value="1" >Contract 1</option>
                            <option value="2" >Contract 2</option>
                            <option value="3" >Contract 3</option>
                            <option value="4" >Contract 4</option>
                            <option value="5" >Contract 5</option>
                            <option value="6" >Contract 6</option>
                            <option value="7" >Contract 7</option>
                        </select>
                    </div>
                    <div class="part-one-left flex space-between">
                        <select name="selectList" class="select-list">
                            <option value="1" >Contract 1</option>
                            <option value="2" >Contract 2</option>
                            <option value="3" >Contract 3</option>
                            <option value="4" >Contract 4</option>
                            <option value="5" >Contract 5</option>
                            <option value="6" >Contract 6</option>
                            <option value="7" >Contract 7</option>
                        </select>
                    </div>
                </div>
                <div class="body-part-two bot50">
                    <div class="part-one-left flex space-between">
                        <select name="selectList" class="select-list">
                            <option value="1" >Contract 1</option>
                            <option value="2" >Contract 2</option>
                            <option value="3" >Contract 3</option>
                            <option value="4" >Contract 4</option>
                            <option value="5" >Contract 5</option>
                            <option value="6" >Contract 6</option>
                            <option value="7" >Contract 7</option>
                        </select>
                        <button class="blue-button">Print</button>
                    </div>
                    <div class="part-one-left column top20">
                        <div class="flex width40 top-bot-40">
                            <p>Contract:</p>
                        </div>
                        {/* {tab === 0 &&
                            <div>
                                <p class="contract-details">There are a wide variety of contracts, ranging from those recommended by insurance companies and state or regional organizations to those generated by individuals. However, a contract is intended to be a legally binding document and, inasmuch as laws can vary from state to state, we recommend that whatever contract you intend to use should be reviewed and sanctioned by a local real estate attorney. <br /><br /> With your authorization, [insert company name] will complete a property inspection conducted in accordance with the standards of practice of the[insert name of organization], a copy of which is available upon request and can be read and downloaded from the Internet at [insert web address]. The inspection is that of a generalist, and has clearly defined limitations. It is performed on-site within a few hours, and does not include any warranty or guaranty. By contrast, specialist inspections take considerably longer, typically include the use of specialized instruments, could involve sampling or destructive testing, and commonly include some form of guaranty. Specialized inspections are essential to evaluate soil conditions, determine structural movement, establish the quality of air and water, or reveal the presence of harmful environmental contaminants such as radon, methane, asbestos, lead, formaldehyde, electro-magnetic radiation, molds and fungi, and other wood-destroying organisms, all of which are beyond the scope of a generalist inspection. Therefore, please be aware of the limitations of a generalist inspection: It is not a termite inspection, which is mandated as a condition of sale and performed by state-licensed specialists. Also, it is not a code-compliance inspection and does not include any research, such as that necessary to establish boundaries, easements, or the issuance of permits, and it should not be used as a substitute for the Transfer Disclosure Statement, which the sellers are required to provide by civil code.</p>
                            </div>
                        }
                        {tab === 1 &&
                            <div>
                                <p class="contract-details">There are a wide variety of contracts, ranging from those recommended by insurance companies and state or regional organizations to those generated by individuals. However, a contract is intended to be a legally binding document and, inasmuch as laws can vary from state to state, we recommend that whatever contract you intend to use should be reviewed and sanctioned by a local real estate attorney.</p>
                            </div>
                        }
                        {tab === 2 &&
                            <div>
                                <p class="contract-details">There are a wide variety of contracts, ranging from those recommended by insurance companies and state or regional organizations to those generated by individuals. However, a contract is intended to be a legally binding document and, inasmuch as laws can vary from state to state, we recommend that whatever contract you intend to use should be reviewed and sanctioned by a local real estate attorney.</p>

                            </div>
                        }
                        {tab === 3 &&
                            <div>
                                <p class="contract-details">There are a wide variety of contracts, ranging from those recommended by insurance companies and state or regional organizations to those generated by individuals. However, a contract is intended to be a legally binding document and, inasmuch as laws can vary from state to state, we recommend that whatever contract you intend to use should be reviewed and sanctioned by a local real estate attorney.</p>

                            </div>
                        }
                        {tab === 4 &&
                            <div>
                                <p class="contract-details">There are a wide variety of contracts, ranging from those recommended by insurance companies and state or regional organizations to those generated by individuals. However, a contract is intended to be a legally binding document and, inasmuch as laws can vary from state to state, we recommend that whatever contract you intend to use should be reviewed and sanctioned by a local real estate attorney.</p>

                            </div>
                        }
                        {tab === 5 &&
                            <div>
                                <p class="contract-details">Contract 6</p>

                            </div>
                        }
                        {tab === 6 &&
                            <div>
                                <p class="contract-details">Contract 7</p>

                            </div>
                        } */}
                    </div>
                    <div class="part-one-left flex top40">
                        <div class="flex width20">
                            <p>Signature:</p>
                            <label class="custom-file-upload">
                                <input type="file" class="display-none"></input>
                                Choose file
                            </label>
                        </div>
                    </div>
                    <div class="part-two-content">
                    </div>
                    <div class="top175 center">
                        <button class="yellow-button">Save</button>
                    </div>
                </div>
            </section>
        </div>
    );
}

export default Automation;